---

- hosts: all
  become: true
  tasks:

  - name: update repo index and install apache and php package for Ubuntu/Debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == ["Ubuntu", "Debian"]

  - name: update repo index and install apache and php package for CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == ["CentOS"]
